### PR TITLE
Fix docs and readme broken links

### LINKED ISSUE #68: Wrong links in Docs Menu
hey guys!
first of all, thanks for your work on doing this framework.

An issue I have is that the main menu of the documentation has some broken links.
I think it's just for COMP and LAYER sections. The link has an extra "_" before ".html" ... if you remove this, you can see the page.

Some examples:
https://aenhancers.github.io/aequery/aeq.Comp_.html#forEachLayer
https://aenhancers.github.io/aequery/aeq.Layer_.html#addEffect

cheers

### PR DESCRIPTION
**Pull request by evefalcao**
This fixes #68 and the link to the documentation on the README file.

### CODE REVIEW

**Comment by zlovatt** [comment]
@evefalcao Have you confirmed that the gulpfile fix _is_ unnecessary? It's our current understanding that there's a conflict due to `aeq.Comp` and `aeq.comp` namespaces, and the docs system is adding the underscore on build.

If that's the case, and it's consistently doing so, then wouldn't the gulpfile step be required to disambiguate this?

**Comment by evefalcao** [comment]
Yes, I have confirmed that the docs build generates the file with the correct casing. However, at some point, the files were committed with the wrong casing. As a result, even when the files are generated with the proper casing, git was tracking them with the wrong name. A fix or workaround was necessary to address this. Now that the files have the correct name in git, the problem has been fixed at its root and the workaround is no longer necessary.

**Comment by zlovatt** [comment]
@evefalcao I've switched the target from `master` to `develop` – if you have a sec could you handle the above little conflicts in these file namings? Then will merge in!

**Comment by evefalcao** [comment]
I resolved the conflict by merging the development branch and regenerating the documentation. Several other files were modified due to outdated documentation in the develop branch.

**Comment by zlovatt** [comment]
Thank you!

**Pull request merged**
